---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: hotels
data:
  DB_PATH: '/db/hotels.json'
  DB_TABLE: 'hotels'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
  namespace: hotels
  labels: 
    app: hotels
    type: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hotels
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: hotels
        type: backend
    spec:
      containers:
        - name: hotels
          image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
          ports:
            - containerPort: 5000
              name: backend
          envFrom:
            - configMapRef:
                name: backend-config
          livenessProbe:
            httpGet:
              path: /status
              port: backend
            failureThreshold: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: backend
            failureThreshold: 2
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /status
              port: backend
            failureThreshold: 30
            periodSeconds: 20
