---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: hotels
  name: hotels

---

# Vamos a catalogar la aplicación con un label llamado "type",
# donde definimos si es la versión "monolith" o "microservices"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
  namespace: hotels
  labels: 
    app: hotels
    type: monolith
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
        type: monolith
    spec:
      containers:
        - name: hotels
          image: ghcr.io/go-elevate/k8s4arch-hotels:monolith