apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
  namespace: hotels
  labels: 
    app: hotels
    type: microservices
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hotels
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: hotels
        type: microservices
    spec:
      containers:
        - name: hotels
          image: ghcr.io/go-elevate/k8s4arch-hotels:monolith-v2
          ports:
            - containerPort: 80
              name: web
          livenessProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 2
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 30
            periodSeconds: 20
