---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: hotels
data:
  DB_PATH: '/db/hotels.json'
  DB_TABLE: 'hotels'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
  namespace: hotels
  labels: 
    app: hotels
    type: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotels
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: hotels
        type: backend
    spec:
      initContainers:
        - name: migrations
          image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          envFrom:
            - configMapRef:
                name: backend-config                          
          command: ["python"]
          args: ["migrations.py"]
          volumeMounts:
            - name: db
              mountPath: /db/
      containers:
        - name: backend
          image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 5000
              name: backend
          envFrom:
            - configMapRef:
                name: backend-config
          volumeMounts:
            - name: db
              mountPath: /db/                
          livenessProbe:
            httpGet:
              path: /status
              port: backend
            failureThreshold: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: backend
            failureThreshold: 2
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /status
              port: backend
            failureThreshold: 30
            periodSeconds: 20
        - name: frontend
          image: ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 5000
              name: frontend
          envFrom:
            - configMapRef:
                name: backend-config
          livenessProbe:
            httpGet:
              path: /status
              port: frontend
            failureThreshold: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: frontend
            failureThreshold: 2
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /status
              port: frontend
            failureThreshold: 30
            periodSeconds: 20
      volumes:
        - name: db
          emptyDir: {}